### ISSUE TITLE
Demo should tell the user to click somewhere (not on AI on/off switch) first

### ISSUE THREAD

**Issue by Zireael07** [WoodyLetsCode/ai-hand-detection#1]
Due to API changes, if the user doesn't click elsewhere first, enabling the system will fail due to pointer lock error

**Comment by w00000dy** [comment]
Hi!
I could not reproduce the error in a hurry. Can you tell me on which devices and browsers you tested it?

**Comment by Zireael07** [comment]
Desktop PC, Linux Manjaro, Vivaldi browser.

**Comment by w00000dy** [comment]
After conducting some tests, it appears that the issue is specific to the Vivaldi browser. The same functionality works seamlessly in Firefox and Chrome. For instance, when examining this [pointer lock example](https://mdn.github.io/dom-examples/pointer-lock/), it is evident that Vivaldi exhibits buggy behavior, while Firefox and Chrome do not exhibit any such issues.
